pipeline {
    agent any
    
    // environment {
    //     SEMGREP_APP_TOKEN = credentials('SEMGREP_APP_TOKEN')
    // }

    stages {
        stage('semgrep scan') {
            steps {
                echo "reaching...."
                sh "semgrep scan --config auto --output devsecops/semgrepscanjuiceshop_results.json --json --exclude='devsecops'"
                echo "rererer..."
            }
        }
        stage('push in defectdojo') {
            steps {
                echo 'Hello World'
            }
        }
    }
}
