pipeline {
    agent any
    
    // environment {
     // SEMGREP_APP_TOKEN = credentials('SEMGREP_APP_TOKEN')
    // }

    stages {
        stage('retire scan') {
            steps { 
                echo "retire started"
                sh 'pwd'
                //sh 'nvm --version'
                //sh 'npm --version'
                //sh 'node --version'
                sh 'retire --version'
                //sh 'retire --outputformat json --outputpath devsecops/retire_scan_results.json'
                //sh 'retire'
                echo "retire completed"
            }
        }
        stage('push in defectdojo') {
            steps {
                echo 'Hello World'
            }
        }
    }
}
